spring.application.name=task

TEST_MODE=1

# Use Render’s assigned port
server.port=${PORT:8080}


# PostgreSQL Configuration

spring.datasource.url=jdbc:postgresql://dpg-d5srpbvpm1nc73cjjo10-a.singapore-postgres.render.com/task_hkpj
spring.datasource.username=task_hkpj_user
spring.datasource.password=BiGunwKBza6mp6MB8hyvSDa73e0xQarf
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true